theme = "hyde"
baseURL = "https://psy-pol.netlify.com/"
languageCode = "de-De"
title = "psy_pol"


license = "MIT"
description = "Blog zur Psychologie des öffentlichen Zeitgeschehens"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "Sebastian Sauer"

[params]
  themeColor = "theme-base-04"
  
  
# If Porting existing theme
[original]
    author =  "Sebastian Sauer"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

