theme = "hyde"
baseURL = "https://psy-pol.netlify.com/"
languageCode = "de-De"
title = "psy_pol"
Author = "Sebastian Sauer"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

license = "MIT"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

 

[params]
    themeColor = "theme-base-0d"
    GitHubUser = "sauer_sebastian"
    description = "Blog zur Psychologie des öffentlichen Zeitgeschehens, von Sebastian Sauer"


[params.social]
    github = "sauer_sebastian"
  


